Column {data-width=205}
----------

### Options

```{r}
inputPanel(
    selectInput(
        inputId = "shipType",
        label = "Vessel Type",
        choices = names(main$shipTypeName)
    ),
    selectInput(
        inputId = "shipName",
        label = "Vessel Name",
        choices = main$shipTypeName[[1]]$ShipName
    )
)
```

```{r}
observeEvent(
    eventExpr = input$shipType,
    handlerExpr = {
        x <- main$shipTypeName[[input$shipType]]$ShipName
        updateSelectInput(
            session = session,
            inputId = "shipName",
            choices = x
        )
    }
)
```

```{r}
shipSelected <- eventReactive(
    eventExpr = c(
        input$shipType,
        input$shipName
    ),
    valueExpr = {
        x <- main$shipMaxDist %>%
            filter(
                ShipType == input$shipType,
                ShipName == input$shipName
            )
        validate(
            need(
                expr = nrow(x) > 0,
                message = "Selection updating, please wait a moment."
            )
        )
        return(x)
    }
)
output$shipSelectedNote <- renderText(
    shipSelectedNoteCreate(shipSelected())
)
hr()
htmlOutput("shipSelectedNote")
```

Column {data-width=795}
----------

### Map

```{r}
output$shipSelectedMap <- renderLeaflet({
    x <- shipSelected()
    y <- leaflet(data = x) %>%
        addProviderTiles("CartoDB.Positron") %>%
        addCircleMarkers(
            lng = ~Lon,
            lat = ~Lat,
            color = "#FF0000"
        ) %>%
        addMarkers(
            lng = ~Lon,
            lat = ~Lat,
            popup = ~paste(
                sprintf("Vessel name: <b>%s</b>", ShipName),
                sprintf("Vessel type: <b>%s</b>", ShipType),
                sprintf("Longitude: <b>%s</b>", Lon),
                sprintf("Latitude: <b>%s</b>", Lat),
                sprintf("Port: <b>%s</b>", Port),
                sprintf("Datetime: <b>%s</b>", Datetime),
                sprintf("Time since last observation (seconds): <b>%s</b>", format(TimeSinceLast_Seconds, big.mark = ",")),
                sprintf("Distance since last observation (meters): <b>%s</b>", format(round(DistSinceLast_Meters), big.mark = ",")),
                sep = "<br>"
            )
        )
    if (!is.na(x$DistSinceLast_Meters)) {
        y <- y %>%
            addCircleMarkers(
                lng = ~PreviousLon,
                lat = ~PreviousLat,
                color = "#000000"
            ) %>%
            addMarkers(
                lng = ~PreviousLon,
                lat = ~PreviousLat,
                popup = ~paste(
                    sprintf("Vessel name: <b>%s</b>", ShipName),
                    sprintf("Vessel type: <b>%s</b>", ShipType),
                    sprintf("Longitude: <b>%s</b>", PreviousLon),
                    sprintf("Latitude: <b>%s</b>", PreviousLat),
                    sprintf("Port: <b>%s</b>", PreviousPort),
                    sprintf("Datetime: <b>%s</b>", PreviousDatetime),
                    sep = "<br>"
                )
            )
    }
    y <- y %>%
        addLegend(
            position = "bottomright",
            title = "Consecutive Observation Type",
            colors = c("#000000", "#FF0000"),
            labels = c("Previous", "Current")
        )
    return(y)
})
leafletOutput("shipSelectedMap")
```
